### ISSUE TITLE
과제 4 설정 관련 질문

### ISSUE THREAD

**Issue by hahjiseong** [kbdlab/walking_robot#10]
과제4 피피티 4장에 다음과 같이 배드 없음 서포트 다음 방향 이라 되있는데요,

1) 배드 없음이 베드 고정이 없다는 의미인가요?

2) 서포트는 그림에 되있는데로 하면 되나요? 그냥 '서포트'로 적혀있으니 명확하지 않아서 헷갈리네요.

3) 다음 방향이 도대체 무슨 의미인가요? 메인프레임을 회전시켜서 그림과 같은 포지션을 취하도록 하란 의미인가요??

**Comment by kbdlab** [comment]
너무 늦어서 이미 제출하였겠지만, 1번은 맞고, 2번은 서포트를 배드가 닿는면 부터 생성하면 됩니다.
3의 방향 프린팅 시간이 2시간 이내로 나오는 방향이라면 상관 없습니다.

과제 채점 시 지정되지 않는 부분이나 애매한 부분은 고려해서 채점하도록 하겠습니다.
