### ISSUE TITLE
1인팀 점수배정 관련 질문

### ISSUE THREAD

**Issue by hahjiseong** [kbdlab/walking_robot#12]
2차 프로젝트부터 팀으로 하게되는데 1인 1팀인거랑 2인 1팀인거랑 점수 배정이 다른가요? 다르다면 어느 정도로 다른가요??

**Comment by kbdlab** [comment]
따로 교수님이 공지하실 예정입니다.

**Comment by Soo-Hong** [comment]
현재 2팀만 1인 1조입니다. 별도로 평가합니다.
