### ISSUE TITLE
Creo 에서 메카니즘의 Dynamic analysis를 할 수 있나요?

### ISSUE THREAD

**Issue by erickwon9** [kbdlab/walking_robot#14]
물성치 등등을 셋팅해서, 시뮬레이션할 때 각 링크 또는 관절에 걸리는 힘, 바닥에 전달되는 동력을 알 수 있는지 궁금합니다.

**Comment by kbdlab** [comment]
학생용 라이센스에서는 불가능한 것으로 알고 있습니다. 가능하더라도 매우 제한적으로만 가능할 것 같네요.

**Comment by aegggsehyun1994** [comment]
Closing
