### ISSUE TITLE
라즈베리파이, 카메라, 배터리, 모터 드라이버, 초음파 센서, 기어 모터의 스펙과 규격 및 모델명이 궁금합니다. 

### ISSUE THREAD

**Issue by ywlee0305** [kbdlab/walking_robot#17]
라즈베리파이, 카메라, 배터리, 모터 드라이버, 초음파 센서, 기어 모터의 스펙과 규격 및 모델명이 궁금합니다. 혹시 위 부품이외에 부가적으로 필요한 부품이 있다면 그것도 추가해서 알려주시면 감사하겠습니다. 
혹시 out파일에 있는 모델 수치들이 실제 모델과 동일한건가요? 이 모델을 그대로 참고해서 만들어도 문제가 없을까요??

**Comment by kbdlab** [comment]
out 폴더 내의 Hardware 라고 되어 있는 폴더 안에 있는 모든 구성요소는 실제 이름입니다.

라즈베리 파이 Raspberry Pi B vi.2
카메라 RPI Camera (G) 또는 (I) - 둘 중 하나로 드립니다. 성능상 차이는 거의 없고 크기 차이만 납니다.
모터 드라이버 L9110
모터 : 150:1 micro metal gear motor 6V HPCB

이상 모델은 매우 정밀하게 일치합니다. 라즈베리 파이와 모터는 동일하다 봐도 됩니다.

배터리 : 샤오미 5000 mAh 배터리, 배터리는 절반은 샤오미 배터리, 절반은 즈미 배터리로 아직 모두 도착하지 않았습니다. 먼저 모델을 내는 분들은 선택할 수 있고, 나중에 내는 분들은 즈미 배터리를 드리도록 하겠습니다. 둘다 성능은 5V / 2A 입니다. 샤오미 배터리의 경우 거의 일치하나 원호부분이나구성 요소 위치가 조금씩 다르고, 즈미 배터리는 아직 도착하지 않아 모델이 없습니다. 크기 차이는 크게 없다고 보고 있습니다.

IMU : MPU6050, 그러나 실제 구입한건 MPU9250 입니다. 이것 역시 도착하면 드리겠습니다.

배터리 부분은 약간의 여유를 두시고, 나머지는 그대로 사용해도 됩니다. IMU는 설치할 생각이 있다면  공간 정도만 확보해주세요.
