### ISSUE TITLE
v-rep converter설정 관련 질문

### ISSUE THREAD

**Issue by hahjiseong** [kbdlab/walking_robot#18]
v-rep converter에 설정 부분에서 궁금한 점이 생겼는데요,

1) 다리 밀도가 1차 프로젝트에선 변경을 할수 있었잖습니까? 근데 3d 프린팅을 하게 되면 아무래도 프린팅 재료가 다 같을 테니 다리 밀도가 특정값 +- a로 고정되는거 아닌가요???(다리 형상이 다 다르니 생기는 그에 따른 오차를 생각하더라도) 맞다면 그 값은 얼마인가요?

2) 설정 부분에서 모터 회전 속도가 degree/s 으로 되있는데 여기서 degree 단위가 육십분법 맞나요?? 맞다면 2차 프로젝트에서 모터 회전 속도는 30~120rpm 으로 생각하면 된다고 하셨던걸로 기억나는데 그럼 v-rep 설정값으로 치환하면 180~720 degree/s 맞나요?

3)  모터 토크는 v-rep 기본 설정과 같이 실제로도 20Ncm 인가요?

**Comment by kbdlab** [comment]
1. 당연히 변경 가능합니다. 실제 재료인 PLA의 밀도는 1.2 g/㎤ 이며, 실제로는 내부 채움 밀도가 100% 가 아니라 더 작습니다. 크기가 커질수록 밀도가 떨어지니 0.6~1.2 g/㎤ 로 생각하시면 되겠습니다.
그리고 V-REP3 상 구조가 무너지는 것을 물리적으로 막을 방법이 있습니다. 수요일에 알려드릴 예정이었는데, 모델을 만약 내신다면 일다 내주시고, 나중에 다리 부분만 약간 수정하면 됩니다.

2. 맞습니다. 실제 모터는 최고 속도가 210 RPM으로 1260 degree / s 입니다. 물론 이건 아무런 로드가 없을 때를 기준으로 한 것이고, 링크 무게 및 마찰, 입력 전류량 등을 고려하면 720 degree / s 를 넘기게 하기도 힘듭니다.

3. 정확히는 스톨 토크가 2.4 kg·cm 이며 자세한 사항은 https://www.pololu.com/product/997 이곳을 참고해주세요.
