### ISSUE TITLE
3D 모델링 시에 다리를 제외한 나머지 부품들의 무게는 얼마정도인가요?

### ISSUE THREAD

**Issue by higun2** [kbdlab/walking_robot#19]
다리를 제외하고,
프레임의 무게는 모델의 디자인시 설정이 가능할 것이라 생각합니다.
그 외의 카메라나 라즈베리 파이, 배터리 무게의 무게는 얼마정도인지 궁금합니다.

또 제공되는 볼트의 길이의 볼트의 종류를 알고 싶습니다.
혹시 제공되지 않는다면 저희가 직접 사서 사용해도 가능한가요?

**Comment by kbdlab** [comment]
가지고 있는 저울의 오차가 1g 단위입니다. 1g 이하 무게는 10개 기준으로 하였습니다.

배터리 (샤오미) : 162 g
10cm 5핀 케이블 : 8 g 
라즈베리 파이 : 42 g
카메라, RPi Camera (I) : 16 g
카메라, RPi Camera (g) : 7 g
초음파 센서 : 9 g

- M2 × 10 mm : 0.2 g
- M3 × 10 mm : 0.6 g
- M4 × 60 mm : 5 g
- 점퍼 케이블 : 10cm 당 0.6 g (10~15개 정도 들어감)

카메라는 선 포함 무게입니다. 
IMU는 안재봤는데 5g 정도일것 같고, 모터드라이버는 초음파 센서와 비슷할 것 같네요.

공개 모델의 경우, 전체 질량은 398 g이고, 일반적으로 350 ~ 600 g 정도로 무게가 나갑니다. 3d 프린팅 파트 질량은 3DWOX 프로그램에서 보면 알 수 있습니다. 서포트가 포함된 무게이니 그 점은 주의해주세요. 

2차 프로젝트 PPT에 질량 조건 미준수 감점이 있었는데 해당 조는 질량이 800 g을 넘겨서 그렇습니다. 자세한 내용은 중간고사 끝나고 다시 한 번 정리해드리겠습니다. 


볼트는 관련 공지가 있으니 참고해주세요. 일단 없는 것은 구매 요청을 받을 텐데, 구매처도 또한 같이 조사해서 받을 예정입니다.
