### ISSUE TITLE
stl파일 하나에 gcode파일 하나 or stl파일 여러개를 gcode파일 하나

### ISSUE THREAD

**Issue by alse426** [kbdlab/walking_robot#20]
stl파일을 gcode로 변환 할 때 stl파일 하나씩 gcode로 변환하나요

아니면 stl파일 여러개를 gcode파일 하나로 변환하나요?

**Comment by kbdlab** [comment]
여러개를 동시에 배치하여 프린팅 가능할경우 여러개를 동시에 변환합니다.
