### ISSUE TITLE
과제5에서 컴퓨터 선공일 때 컴퓨터가 필패하는 경우는 어떻게 하나요

### ISSUE THREAD

**Issue by alse426** [kbdlab/walking_robot#21]
예를 들면 N=29, n=3일 때

4를 먼저 부른 사람이 이기는데

컴퓨터가 선공이면 후공인 플레이어가 무조건 4를 부를 수 있잖아요

이처럼 컴퓨터가 선공이지만 필패하는 상황의 조건은 어떻게 되나요?

**Comment by inwk** [comment]
(N-1)/(n+1)의 나머지가 0일 경우에는 임의의 숫자를 부른 후 필승전략을 적용할 수 있는 상황이 오면 
그 시점부터 적용한다고 조건4에 나와있네요!

**Comment by kbdlab** [comment]
윗분 말씀대로 (N-1)/(n+1)의 나머지가 0인 경우입니다. 조건4를 조금 더 자세히 설명드리겠습니다.
컴퓨터가 처음부터 필승 전략을 적용할 수 없는 상황이고 플레이어가 계속해서 필승전략을 사용한다면 컴퓨터가 집니다. 하지만 플레이어가 단 한번이라도 실수할 경우 컴퓨터는 그 순간 곧바로 필승전략을 사용하도록 코딩해 주시면 됩니다.
