### ISSUE TITLE
ssh 설치 시 upgrade 입력 후 오류가 발생합니다.

### ISSUE THREAD

**Issue by higun2** [kbdlab/walking_robot#24]
![캡처](https://user-images.githubusercontent.com/56909661/68181404-7e64cf00-ffda-11e9-97da-70305c295c8d.JPG)

이와 같은 오류가 발생하며 업그레이드가 진행되지 않는데 해결방법을 알고 싶습니다.

**Comment by higun2** [comment]
무시하고 ssh 설치를 진행했는데 상관 없나요?

**Comment by erickwon9** [comment]
같은 증상을 겪고있습니다. 무시하고 진행하셨을때 문제 없나요?

**Comment by Leeinhak** [comment]
위에 탭에서 CODE로 들어가신 후 readme를 보시면 해결방법이 나와있습니다.
