### ISSUE TITLE
카메라 모델명 또는 크기를 알고 싶습니다.

### ISSUE THREAD

**Issue by malgiheo-eon** [kbdlab/walking_robot#26]
와이섹에 올라와 있는 카메라 캐드 파일과 크기가 달라서 카메라 홀더를 만들수 가 없습니다.
 모델명 또는 규격을 알려 주셨으면 합니다

**Comment by kbdlab** [comment]
작은 것은 RPi Camera (G), 큰 것은 RPi Camera (I) 입니다.
https://yscec.yonsei.ac.kr/mod/jinotechboard/content.php

이곳 parts 안의 RPi Camera (G)는 제가 직접 체크도 해서 크기가 정확히 맞을 겁니다. (I)는 조금 다를 수도 있겠네요.

**Comment by malgiheo-eon** [comment]
답변 감사합니다, 그런데 제 기기 문제인지는 모르겠지만 핸드폰과 노트북 모두에서 링크가 안들어가집니다,. 링크를 한번 더 확인 해주실 수 있나요?

**Comment by kbdlab** [comment]
링크 확인을 따로 안했었는데 10월 25일에 올린 '부품 공지 및 질량 조건 제한(10월 30일 업데이트)' 이겁니다.
