### ISSUE TITLE
카메라 케이블 관련 문의

### ISSUE THREAD

**Issue by hyuk95** [kbdlab/walking_robot#27]
기본으로 주어진 카메라 케이블(15cm)가 짧아서 안 닿는데 혹시 20cm 이상인 케이블이 연구실에 있나요?

**Comment by Leeinhak** [comment]
현재 연구실에 남은 케이블 길이는 기존에 나눠드린 길이와 동일한 크기만 남아있습니다. 따로 더 연장된 케이블을 필요로 하시면 따로 구매 해주셔야 할 것 같습니다..
