### ISSUE TITLE
AR마커 관련

### ISSUE THREAD

**Issue by joonha2006** [kbdlab/walking_robot#29]
Marker-피피티 내의 AR마커 관련 링크(깃허브)에 첨부되어 있는 사진은 총 6장입니다. 각각의 ar마커들은 어떤 방향을 의미하는 것인가요? 브이랩 상에서의 가야하는 경로를 따라가는 건가요? 직진, 좌회전, 우회전 외의 방향지시가 있는지 궁금합니다.

**Comment by kbdlab** [comment]
마커들은 공통된 규칙에 따라 있으며 V-rep 상의 화살표 방향이나 2차 프로젝트를 참고하셔서 규칙을 만들면 됩니다. 단, 2차 프로젝트 기준 2구간 끝부분은 더이상 들어가지 않습니다.

각 마커의 위치를 보면 우회전/좌회전/정지 3가지 규칙 중 하나를 선택하면 된다는 것을 알 수 있습니다. 겹칠수도 있고요. 번호는 PPT나 scanner 코드를 참고해주세요.
