### ISSUE TITLE
cascade training 관련 질문

### ISSUE THREAD

**Issue by hahjiseong** [kbdlab/walking_robot#30]
cascade training 을 하려는데 train 버튼을 누르면 계속 다음 사진과 같이 오류가 뜹니다. 또 어쩔땐 out of memory라고 뜰때도 있구요, 어느 부분이 문제인가요?????
<img width="1920" alt="dedddddddddddddddddddddd" src="https://user-images.githubusercontent.com/56431846/70031143-f7614180-15ed-11ea-9545-51d400a27928.png">

**Comment by kbdlab** [comment]
왼쪽에서 사이즈는 24,24인데 오른쪽은 50,50이네요. 일단 50,50 크기는 너무 커서 out of memory가 나올 확률이 높습니다. 40,40 정도는 가능합니다.

이미지 사이즈도 24,24이든 40,40인든 지정한 대로 맞추어주셔야합니다.
