### ISSUE TITLE
AR마커 관련  문의

### ISSUE THREAD

**Issue by hyuk95** [kbdlab/walking_robot#32]
AR마커를 경로상에서 치우는 것도 가능한가요? 
(처음 부터 치우고 시작 )

**Comment by kbdlab** [comment]
AR 마커를 치우고하는 건 상관은 없는데, 그렇다면 어떤 방식으로 길을 인식하고 가는지에 대해 설명해주셔야합니다. AR 마커는 사실 좌/우/전진 기준을 간단히 알게하기 위해서 드리는 것이기 때문에 질문만 보고 굳이 치우는 이유를 알 수 없네요.

아무튼 방법에 따라서는 실격이 될 수 있고, 창의적 기능으로 보고 가산점이 붙을 수 있습니다.
