### ISSUE TITLE
np.max 문법 질문입니다.

### ISSUE THREAD

**Issue by erickwon9** [kbdlab/walking_robot#33]
image[180:220][center].max(axis=1)==255

하면

index 159 is out of bound for axis 0 with size 40 라고 오류가 뜹니다.

center = 159 입니다. axis를 0과 1, 2 다 바꿔가면서 했는데 안되네요

**Comment by kbdlab** [comment]
np.max 문제가 아닙니다.
image[180:220][center] 이렇게만 쳐도 같은 오류가 납니다.

해결 방법은 
> image[180:220,center].max(axis=0)
와 같이 쓰는 것입니다.

image[180:220][center] 와 같이 쓰면 image[180:220] 라는 40개짜리 array의 center 번째 index로 검색되기 때문입니다. 

반대로 image[240][0:10] 과 같은 표현은 괜찮습니다.
