### ISSUE TITLE
v-rep 관련 질문입니다.

### ISSUE THREAD

**Issue by ywlee0305** [kbdlab/walking_robot#35]
파일을 실행하면 속도가 빨라 측정 시간이 끝나기도 전에 로봇이 추락합니다.

 coppeliasim에서 지형의 크기를 더 크게 해서 실행해도 될까요?

**Comment by ywlee0305** [comment]
![image](https://user-images.githubusercontent.com/56719635/94393395-cf068d00-0195-11eb-9294-ae0a166449aa.png)

**Comment by aegggsehyun1994** [comment]
네 그렇게 하셔도 좋습니다

**Comment by aegggsehyun1994** [comment]
#37 에 지형 넓히는 방법 좀 답변으로 남겨주시겠어요?

**Comment by ywlee0305** [comment]
#37 에 답변 남겼습니다.
