### ISSUE TITLE
4주차 숙제와 1차 프로젝트 관련 질문입니다!

### ISSUE THREAD

**Issue by changhyun-na** [kbdlab/walking_robot#36]
4주차 숙제 모델을 어셈블리 할때 다리의 property 들이 지난번에 만들었던 v-rep 컨버터 상의 leg properties (number, gap, width, thickness)과 모두 일치해야 하나요? 아니면 새로운 얀센비만 일치하면 되나요? 만약 모두 일치해야 한다면 gap 같은 경우에는 다리 연결부를 다리 사이에 간격을 갖도록 새로 모델링해야 하나요?

그리고 1차 프로젝트를 진행할 때는 3, 4주차때 만든 메커니즘과는 또 다른 새로운 얀센비 메커니즘으로 처음부터 새로 만들어야 하는 것인가요?

**Comment by dong9411** [comment]
숙제는 꼭 일치하거나 할 필요 없었습니다.
1차 프로젝트도 전에 만든 것을 쓰셔도 됩니다.
