### ISSUE TITLE
1차 프로젝트 질문입니다

### ISSUE THREAD

**Issue by changhyun-na** [kbdlab/walking_robot#38]
v-rep 시뮬레이션 조건 중에 "leg angle limit 기능 사용 불가" 라는 조건이 있는데, 아래 화면에서 excute와 체크박스 체크를 모두 안 한 상태로 시뮬레이션에 성공하여야 하는건가요??
저게 없이는 다리가 꼬이고 주저앉는 현상이 계속 발생하는데, 그것을 다른 방법으로 해결하는 것이 프로젝트의 목적인건가요?
![image](https://user-images.githubusercontent.com/72072474/94984905-29379180-058c-11eb-88c4-0221bde5bb6e.png)

**Comment by dong9411** [comment]
맞습니다.
