### ISSUE TITLE
CAD 및 V-Rep Converter 채점 기준

### ISSUE THREAD

**Issue by tomato1mule** [kbdlab/walking_robot#39]
1. V-rep 시뮬에 사용된 width와 thickness 및 leg gap은 CAD와 동일해야하나요? 그렇다면 leg gap은 메커니즘 특징상 균일하게 맞출 수가 없을 것 같은데 평균으로 사용하면 될까요?

2. V-rep converter의 csv output에 적힌 로봇의 크기 및 중량이 V-rep converter 프로그램에 뜨는 실제 값보다 작게 적히는 버그가 있는데 그냥 제출해도 무방한가요?

**Comment by dong9411** [comment]
1. CAD는 형태나 설계 타당성 위주로 평가되기 때문에 링크비율을 제외한 세부 수치는 시뮬레이션과 정확히 동일하지 않아도 상관없습니다.
2. 네 괜찮습니다.
