### ISSUE TITLE
1차 프로젝트 관련 질문

### ISSUE THREAD

**Issue by qwertjy** [kbdlab/walking_robot#4]
[1차프로젝트.pptx](https://github.com/kbdlab/walking_robot/files/3700240/1.pptx)

안녕하세요. 

1차 프로젝트 ppt 세 번째 슬라이드 내용 중  모터 토크를 20N*m로 설정하라고 되어있는데 V-rep converter의 Basic setting 탭의 Motor Torque 항목 단위는 N*cm로 되어 있습니다. 2000N*cm로 설정하는 것인지 아니면 슬라이드 내용의 단위 부분이 오타인지 궁금합니다.

**Comment by kbdlab** [comment]
오타입니다. 20 N cm로 해주세요.
