### ISSUE TITLE
9주차 실습과제 질문입니다.

### ISSUE THREAD

**Issue by SuhBoGyeong** [kbdlab/walking_robot#40]
이번주 실습과제 관련해서 질문 드리게 되었습니다.
6자리 번호가 list형태로 5개 나오도록 코딩하라고 되어있는데, 
이때 이 5개의 list가 다른 list의 요소여야 하나요? 즉 2차원 배열을 생성해서 6개의 번호 set를 각 요소로 갖고 있는 배열을 만든 후 이를 출력해야 하나요?
이렇게 하지 않고 첨부한 사진처럼 그냥 6개의 번호를 가진 배열 각각을 출력하게끔 코딩하였는데 이렇게 해도 괜찮은건지 궁금합니다.
감사합니다. 
![code](https://user-images.githubusercontent.com/73596975/97445805-002ed480-1971-11eb-87e7-111d86002517.JPG)

**Comment by kbdlab-pdh** [comment]
네 말씀하신대로 2차원 배열로 출력하셔야 합니다.
