### ISSUE TITLE
TeamViewer 

### ISSUE THREAD

**Issue by Reversable** [kbdlab/walking_robot#41]
실습 시간에 알려주신 대로 

(모니터 없는 경우)
window powershell 통해서 라즈베리파이에 teamviewer 설치 하고
setup, login까지 했습니다.

그리고 나서 노트북에서 teamviewer 접속해 라즈베리파이 원격 제어를 하려고 하는데
![image](https://user-images.githubusercontent.com/69837335/98070952-98631700-1ea5-11eb-9102-db5994a192c4.png)
첨부한 이미지와 같이 연결이 계속해서 실패합니다.

재부팅 후 시도해봤지만 계속해서 에러가 납니다.
어떻게 해야하나요?

**Comment by dong9411** [comment]
혹시 메일 인증하셨나요?

**Comment by Reversable** [comment]
넵 
![image](https://user-images.githubusercontent.com/69837335/98201758-c0b94700-1f73-11eb-86d9-1897bb786eef.png)

이메일 인증도 했습니다.

**Comment by dong9411** [comment]
sudo teamviewer license accept해보시고 안되면
sudo teamviewer info 스크린샷 찍어서 한번 보여주실래요?

**Comment by Reversable** [comment]
license 는 accept 되었다고 떴습니다.

해결이 안돼서 image 재설치부터 몇 번 반복하니 해결됐습니다. 감사합니다.
