### ISSUE TITLE
OpenCV 관련 오류 질문입니다.

### ISSUE THREAD

**Issue by lcho3878** [kbdlab/walking_robot#42]
비주얼 스튜디오 코드를 사용하여 코드를 짜서 실행하면

cv2.imshow를 할경우에 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/user/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. 라는 메시지가 뜨면서 화면이 출력되지 않습니다.

plt.imshow를 하게되면 오류는 나지 않지만 화면도 출력되지 않습니다. 

코드는 ppt에 있는 코드를 그대로 이미지의 경로만 변경해서 사용했습니다. 
![12](https://user-images.githubusercontent.com/74814587/99872447-38020280-2c25-11eb-892a-8f61cf8fa026.png)

**Comment by aegggsehyun1994** [comment]
현재 SSH로만 연결을 해두셨고 라즈베리 파이가 GUI를 출력하고 있지 않은 상황으로 보이네요.
저 오류는 imshow가 이미지를 창을 새로 열어 띄우고 싶은데, GUI가 없다, 디스플레이가 없다 이런 뜻입니다. 
저도 디스플레이가 없는 AWS에서 대부분의 개발을 진행하기 때문에 여러분들에게 드린 코드에 저 오류에 대비를 조금 해두었는데요.
[https://github.com/kbdlab/walking_robot/blob/master/Networking/Server.py](url)
위 파일을 보시면 `'DISPLAY' in environ`을 확인하는 부분이 있는데, 이것이 True면 imshow가 되고 아니면 안 될 겁니다.
저 파일 확인해보시고 imshow가 불가능하면

1. 팀 뷰어 사용
2. 이미지 스트리밍
3. 파일로 저장

이 3가지 방법 중 하나를 사용하시면 될 거 같습니다.

**Comment by aegggsehyun1994** [comment]
Closing
