### ISSUE TITLE
프랙탈 과제 질문입니다

### ISSUE THREAD

**Issue by Hyunwoo-Park-Yonsei** [kbdlab/walking_robot#43]
![image](https://user-images.githubusercontent.com/71742893/99881127-158adc00-2c5b-11eb-8f4f-b2d8bbb3b0e6.png)

제 과제를 보시면, 프랙탈 구조이고, 성능 또한 1000x1000임에도, 100x100과 차이가 거의 안납니다.
근데 numpy 라이브러리를 2-3개 밖에 사용하지않았는데, 이에 대한 감점은 없는건지 이에 대한 기준이 궁금합니다, 또한 너무 간단한 프랙탈 구조는 감점이 되는건지 궁금합니다.

**Comment by aegggsehyun1994** [comment]
정의만 만족하면 감점하지 않겠습니다. 성능 평가할 때 쓸 코드를 길어도 며칠 내로 올려드릴테니 참고하시면 될 거 같아요.

**Comment by aegggsehyun1994** [comment]
[Fractal.py](https://github.com/kbdlab/walking_robot/blob/master/Fractal/Fractal.py)

**Comment by aegggsehyun1994** [comment]
[Fractal.py](https://github.com/kbdlab/walking_robot/blob/master/Fractal/Fractal.py)
