### ISSUE TITLE
이미지 스트리밍(ImageRW.py) 오류가 나서 질문드립니다 

### ISSUE THREAD

**Issue by 16Kim-Sol** [kbdlab/walking_robot#51]
안녕하세요, 이미지 스트리밍 코드를 실행시키다 중간에 오류가 나서 질문드립니다. 

![imageRW_download](https://user-images.githubusercontent.com/75159494/100535672-56d44a80-325e-11eb-80df-376f79e9ba55.jpg)

첫번째 사진과 같이 line46의 다운로드의 주석만 지우고 코드를 돌리면 steveholt.jpg 파일이 정상적으로 다운로드됩니다.

![imageRW_down_and_upload](https://user-images.githubusercontent.com/75159494/100535798-6902b880-325f-11eb-9d28-7baef107cb4f.jpg)

하지만 두번째 사진과 같이 line47의 업&다운로드의 주석만 지우고 코드를 돌리면 오류가 나오고,

![imageRW_upload](https://user-images.githubusercontent.com/75159494/100535831-a5361900-325f-11eb-8dc2-f1c7c9a022b4.jpg)

세번째 사진과 같이 line48의 업로드의 주석만 지우고 코드를 돌려도 오류가 나옵니다.
오류가 여러곳에서 생긴거같은데, 어느 부분이 문제인지 알려주시면 정말 감사하겠습니다.

**Comment by aegggsehyun1994** [comment]
#44 의 중복입니다. 그대로는 안 돌아가고 코딩을 하셔야 해요.
