### ISSUE TITLE
ar_markers 설치 문제

### ISSUE THREAD

**Issue by Reversable** [kbdlab/walking_robot#55]
안녕하세요.

라즈베리파이에서 pip install ar_markers를 설치하고 설치 여부를 확인하기 위해 간단한 코드를 돌려봤습니다.

 
![image](https://user-images.githubusercontent.com/69837335/101312804-09785e80-3898-11eb-9972-286d222663fc.png)

그런데 위와 같이 
ModuleNotFoundError : No module named 'ar_markers'라는 에러가 계속 뜹니다.
삭제하고 다시 설치해봐도 그대로입니다.ㅠㅠ

해결 방법이 있을까요?

**Comment by sehyun-hwang** [comment]
`pip`이 아니라 `pip3`를 사용하셔야 해요.

**Comment by Reversable** [comment]
감사합니다. 해결되었습니다!
