### ISSUE TITLE
채점기준의 타당성 항목에 관하여

### ISSUE THREAD

**Issue by hyuk95** [kbdlab/walking_robot#6]
타당성 항목은 어떤식으로 평가가 진행되는 건가요?

**Comment by kbdlab** [comment]
타당성은 다른 정량적인 수치 값 자체와는 상관 없이 평가합니다.

타당성은, 모델 설계를 어떻게 진행하였는지에 대한 평가 요소입니다. 단순히 어쩌다가 좋은 모델이 나왔다라고 하는 것보다는, 근거를 들어서 왜 그렇게 모델을 만들었는지, 왜 해당 모델이 그러한 결과가 나왔는지 분석하면서 설명하는 것이 더 좋은 평가를 받습니다.

논리적으로 도출되었다면 속도, 질량 등이 값 자체와는 아무 상관 없습니다.
