### ISSUE TITLE
팀원은 금요일날 바로 나누는건가요??

### ISSUE THREAD

**Issue by inwk** [kbdlab/walking_robot#7]
만약에 금요일날 나눈다면 그자리에서 바로 발표점수를 매겨서 상위50퍼와 하위 50퍼로 나누게 되는건가요?

**Comment by kbdlab** [comment]
채점을 바로 그렇게 빨리 할 수 없기 때문에 그날 바로 나누지는 못합니다. 각 모델 별로 테스트를 해봐야하니까요.  적어도 수업 시간에는 불가능합니다.
