### ISSUE TITLE
공차 설계 관련 질문

### ISSUE THREAD

**Issue by Jaeho-Jin** [kbdlab/walking_robot#8]
이번 1차 프로젝트에도 공차 설계를 해야하나요?

해야 한다면 공차 설계에 대한 정확한 지식이 없어서 어떻게 해야 할지 잘 모르겠습니다.

**Comment by kbdlab** [comment]
사실 처음부터 모두 설계하는 것이 제일 좋겠지만, 너무 어려우면 숙제나 나누어드린 모델 참고하고 수정하는 방향으로 진행해주세요. 저는 그대로 사용하면 감점한다고 했지 수정한 모델까지 감점하지는 않습니다. 길이비율 변경이나 링크 형태, 두께 등을 조정해주세요.

물론 수업 때 언급한 것처럼 아무것도 바꾸지 않고 그대로 사용하면 문제가 되고, 바꾼 내용 
때문에 충돌이 나면 안됩니다.
